swagger: "2.0"
info:
  title: Produk API
  version: 1.0.0
  description: Contoh API untuk produk

schemes:
  - http
  - https

paths:
  /produk:
    get:
      summary: Mendapatkan semua produk
      produces:
        - application/json
      responses:
        200:
          description: Berhasil mendapatkan data produk
          schema:
            type: array
            items:
              $ref: "#/definitions/Produk"
        500:
          description: Terjadi kesalahan pada server

    post:
      summary: Menambahkan produk baru
      produces:
        - application/json
      parameters:
        - in: body
          name: produk
          description: Data produk yang akan ditambahkan
          required: true
          schema:
            $ref: "#/definitions/ProdukInput"
      responses:
        201:
          description: Produk berhasil ditambahkan
        400:
          description: Request tidak valid
        500:
          description: Terjadi kesalahan pada server

  /produk/{id}:
    get:
      summary: Mendapatkan detail produk berdasarkan ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID produk yang akan dicari
          required: true
          type: integer
      responses:
        200:
          description: Berhasil mendapatkan data produk
          schema:
            $ref: "#/definitions/Produk"
        404:
          description: Produk tidak ditemukan
        500:
          description: Terjadi kesalahan pada server

    put:
      summary: Memperbarui data produk berdasarkan ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID produk yang akan diperbarui
          required: true
          type: integer
        - in: body
          name: produk
          description: Data produk yang akan diperbarui
          required: true
          schema:
            $ref: "#/definitions/ProdukInput"
      responses:
        200:
          description: Produk berhasil diperbarui
        400:
          description: Request tidak valid
        404:
          description: Produk tidak ditemukan
        500:
          description: Terjadi kesalahan pada server

    delete:
      summary: Menghapus produk berdasarkan ID
      produces:
        - application/json
      parameters:
        - in: path
          name: id
          description: ID produk yang akan dihapus
          required: true
          type: integer
      responses:
        200:
          description: Produk berhasil dihapus
        404:
          description: Produk tidak ditemukan
        500:
          description: Terjadi kesalahan pada server

definitions:
  Produk:
    type: object
    properties:
      id:
        type: integer
      nama_produk:
        type: string
      harga:
        type: integer
    required:
      - id
      - nama_produk
      - harga

  ProdukInput:
    type: object
    properties:
      nama_produk:
        type: string
      harga:
        type: integer
    required:
      - nama_produk
      - harga

securityDefinitions:
  api_key:
    type: apiKey
    name: api_key
    in: header
